const about = {
    'Adrar': "Known for its vast desert landscapes, Adrar is a gateway to the Sahara and home to stunning oasis towns like Timimoun.",
    'AinDefla': "Ain Defla is famous for its agricultural richness, particularly in olive and cereal production.",
    'AinTemouchent': "Located along the Mediterranean, Ain Temouchent boasts beautiful beaches and is known for its winemaking industry.",
    'Alger': "The capital of Algeria, Algiers, is a mix of French colonial architecture and traditional Casbah, a UNESCO World Heritage site.",
    'Annaba': "Home to Algeria’s largest steel complex, Annaba is also known for its scenic beaches and the historic Basilica of St. Augustine.",
    'Batna': "The heart of the Aurès Mountains, Batna is close to the famous Roman ruins of Timgad, often called 'The African Pompeii'.",
    'Bechar': "A desert city with a rich musical heritage, Bechar is famous for its folklore and the mesmerizing Taghit oasis.",
    'Bejaia': "Known for its breathtaking coastal scenery, Bejaia is a major port city and home to the beautiful Cap Carbon lighthouse.",
    'Biskra': "Nicknamed the 'Gateway to the Sahara,' Biskra is famous for its delicious Deglet Nour dates and warm climate.",
    'Blida': "Surrounded by orange and olive groves, Blida is often called the 'City of Roses' and is known for its proximity to Chréa National Park.",
    'BordjBouArreridj': "A major hub for electronics and technology in Algeria, Bordj Bou Arréridj is often referred to as 'Algeria’s Silicon Valley'.",
    'Bouira': "Home to the majestic Djurdjura Mountains, Bouira is known for its hiking trails and the beautiful Lake Agoulmime.",
    'Boumerdes': "A coastal province near Algiers, Boumerdes is famous for its pristine beaches and vibrant fishing industry.",
    'Chlef': "Known for its agricultural production, Chlef is a major producer of citrus fruits and olives in Algeria.",
    'Constantine': "The 'City of Bridges,' Constantine is built on dramatic cliffs and has stunning bridges, including the iconic Sidi M'Cid bridge.",
    'Djelfa': "Located in the Hauts Plateaux region, Djelfa is famous for its rock carvings dating back thousands of years.",
    'ElBayadh': "A vast province with beautiful steppe landscapes, El Bayadh is home to the mysterious Taghit cave paintings.",
    'ElMeghaier': "A desert oasis rich in palm groves, El Meghaier is known for its natural hot springs and traditional handicrafts.",
    'ElMenia': "A small but beautiful desert town, El Menia is famous for its sand dunes and lush oases.",
    'ElOued': "Nicknamed the 'City of a Thousand Domes,' El Oued is known for its unique architecture and high-quality date production.",
    'ElTarf': "Rich in biodiversity, El Tarf is home to El Kala National Park, which hosts rare species like the Barbary red deer.",
    'Ghardaia': "A UNESCO-listed city, Ghardaia is known for its stunning M'zab Valley and unique Saharan architecture.",
    'Guelma': "Home to hot springs and Roman ruins, Guelma is famous for the Hammam Debagh waterfalls, a natural thermal wonder.",
    'Illizi': "A remote desert province, Illizi is the gateway to the stunning Tassili n'Ajjer National Park, famous for its prehistoric rock art.",
    'Jijel': "Jijel boasts some of Algeria’s most stunning beaches, along with the unique limestone caves of Aouana.",
    'Khenchela': "Surrounded by mountains, Khenchela is famous for its historical Berber heritage and hot springs.",
    'Laghouat': "An oasis city blending desert and greenery, Laghouat is a cultural mix of Arab and Amazigh traditions.",
    'Mascara': "The birthplace of Emir Abdelkader, Mascara is famous for its vineyards and olive oil production.",
    'Medea': "Nestled in the Tell Atlas mountains, Medea is known for its cool climate and rich agricultural lands.",
    'Mila': "Home to the ancient Roman city of Milev, Mila is rich in history and natural beauty.",
    'Mostaganem': "A coastal gem, Mostaganem is known for its lively cultural scene and stunning Mediterranean beaches.",
    'Msila': "Famous for the ruins of Beni Hammad, a UNESCO World Heritage Site, Msila is a historical treasure.",
    'Naama': "A land of vast steppe landscapes, Naama is home to nomadic traditions and Saharan wildlife.",
    'Oran': "Nicknamed 'The Radiant,' Oran is Algeria’s second-largest city, famous for its music, culture, and the Santa Cruz fortress.",
    'Ouargla': "A desert city with a rich trading history, Ouargla is known for its palm groves and traditional markets.",
    'OuedSouf': "An oasis town famous for its underground houses and date palm plantations.",
    'Relizane': "Known for its fertile lands, Relizane is a major center for agriculture and textile production.",
    'Saida': "A charming town with a mix of Ottoman and French colonial history, Saïda is also known for its mineral water sources.",
    'Setif': "A major commercial hub, Setif is home to the impressive Roman ruins of Djemila, a UNESCO World Heritage site.",
    'SidiBelAbbes': "Often called 'The French Oxford,' Sidi Bel Abbes is known for its university and military history.",
    'Skikda': "A coastal city with beautiful beaches, Skikda is also an important oil and gas hub.",
    'SoukAhras': "The birthplace of Saint Augustine, Souk Ahras is rich in Roman history and archaeological sites.",
    'Tamanrasset': "The heart of the Sahara, Tamanrasset is home to the Tuareg people and the stunning Hoggar Mountains.",
    'Tebessa': "A city with a rich Roman heritage, Tebessa is famous for its ancient basilicas and historical ruins.",
    'Timimoun': "A breathtaking oasis town, Timimoun is known for its red mudbrick architecture and stunning desert scenery.",
    'Tindouf': "A remote desert town, Tindouf is an important center for Sahrawi refugee camps and trade routes.",
    'Tipaza': "Famous for its ancient Phoenician and Roman ruins, Tipaza is a UNESCO World Heritage site by the sea.",
    'Tissemsilt': "Home to the stunning Theniet El Had National Park, Tissemsilt is a hidden paradise for nature lovers.",
    'TiziOuzou': "The heart of Kabylie, Tizi Ouzou is known for its Amazigh culture, mountainous landscapes, and delicious olive oil.",
    'Tlemcen': "A historic city with Andalusian influences, Tlemcen is famous for its mosques, palaces, and waterfalls.",
    'Touggourt': "A desert city with a strong Saharan identity, Touggourt is an important date-producing region in Algeria."
};
